language: python
python:
  - "3.6"

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "CREATE USER dave WITH PASSWORD 'pass';" -U postgres

env:
  global:
    - DB_NAME=testdb
    - DB_USER=dave
    - DB_PASSWORD=pass

install: pip install -r requirements.txt
script:
- nosetests -v ./MaintenanceTrackerAPI/_tests/ --with-coverage --cover-package=./MaintenanceTrackerAPI/api/
after_script: coveralls
