language: python
python:
  - "3.6"

install: pip install -r requirements.txt

script: nosetests -v ./MaintenanceTrackerAPI/_tests/ --with-coverage --cover-package=./MaintenanceTrackerAPI/api/
after_script: coveralls
